export const userConstans = {
    USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
    USER_LOGOUT: "USER_LOGOUT",
    USER_REGISTRATION_REQUEST: "USER_REGISTRATION_REQUEST",
    USER_REGISTRATION_SUCCESS: "USER_REGISTRATION_SUCCESS",
    USER_REGISTRATION_FAILURE: "USER_REGISTRATION_FAILURE"
};
